ubuntu-latestname: Testing
on:
  push:
    branches:
    - main
jobs:
  testing:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: print env of the repo
      run: env
